image: docker/compose:latest

stages:
  - deploy

variables:
  PRO_NAME: spotify
  MAIN_URL: marroquin.dev

.variables_master: &master_variables
  variables:
    FULL_URL: ${PRO_NAME}.${MAIN_URL}
  stage: deploy
  only:
    - master
  tags:
    - production
deploy:
  <<: *master_variables
  script:
    - docker-compose -f compose.yml pull
    - docker-compose -f compose.yml --project-name ${PRO_NAME} up -d --build --force-recreate --remove-orphans
  environment:
    name: master
    url: https://${FULL_URL}
stop:
  <<: *master_variables
  when: manual
  script:
    - docker-compose --project-name ${PRO_NAME} stop
  environment:
    name: master
