image: docker/compose:latest

stages:
  - deploy

variables:
  PRO_NAME: spotify
  MAIN_URL: marroquin.dev

.variables_main: &main_variables
  variables:
    SPOTIFY_URL: ${PRO_NAME}.${MAIN_URL}
  stage: deploy
  only:
    - main
  tags:
    - production
deploy:
  <<: *main_variables
  script:
    - docker-compose -f compose.yml pull
    - docker-compose -f compose.yml --project-name ${PRO_NAME} up -d --build --force-recreate --remove-orphans
  environment:
    name: main
    url: https://${SPOTIFY_URL}
stop:
  <<: *main_variables
  when: manual
  script:
    - docker-compose --project-name ${PRO_NAME} stop
  environment:
    name: main
