image: tmaier/docker-compose:latest

stages:
  - deploy

variables:
  PRO_NAME: spotify
  MAIN_URL: marroquin.dev
  MY_EMAIL: luis@marroquin.dev

.variables_master: &master_variables
  variables:
    FULL_URL: ${PRO_NAME}.${MAIN_URL}
  stage: deploy
  only:
    - master
  tags:
    - production
deploy_master:
  <<: *master_variables
  script:
    - docker-compose --project-name ${PRO_NAME}_${CI_COMMIT_REF_NAME} up -d --build --force-recreate --remove-orphans
  environment:
    name: env_master
    url: https://${FULL_URL}
stop_master:
  <<: *master_variables
  when: manual
  script:
    - docker-compose --project-name ${PRO_NAME}_${CI_COMMIT_REF_NAME} stop
  environment:
    name: env_master

.variables_dynamic: &dynamic_variables
  variables:
    FULL_URL: ${PRO_NAME}.${CI_COMMIT_REF_NAME}.${MAIN_URL}
  stage: deploy
  only:
    - branches
  except:
    - master
  tags:
    - production
deploy_dynamic:
  <<: *dynamic_variables
  script:
    - docker-compose --project-name ${PRO_NAME}_${CI_COMMIT_REF_NAME} up -d --build --force-recreate --remove-orphans
  environment:
    name: env_dynamic
    url: https://${FULL_URL}
stop_dynamic:
  <<: *dynamic_variables
  when: manual
  script:
    - docker-compose --project-name ${PRO_NAME}_${CI_COMMIT_REF_NAME} stop
  environment:
    name: env_dynamic
