image: tmaier/docker-compose:latest

stages:
  - deploy

variables:
  URL_NAME: spotify
  BASE_URL: marroquin.dev
  PROJECT_NAME: spotify_app
  USER_EMAIL: luis@marroquin.dev

deploy:
  stage: deploy
  script:
    - echo 'Deploying ${CI_COMMIT_REF_NAME}'
    - docker-compose --project-name ${PROJECT_NAME}_production up -d --build --force-recreate --remove-orphans
  environment:
    name: Production
    url: https://${URL_NAME}.${BASE_URL}
  only:
    - master
  tags:
    - env-production

stop:
  stage: deploy
  when: manual
  script:
    - echo 'Stopping ${CI_COMMIT_REF_NAME}'
    - docker-compose --project-name ${PROJECT_NAME}_production stop
  environment:
    name: Production
  only:
    - master
  tags:
    - env-production
