version: '3.8'

networks:
  external:
    name: nginx-proxy
  internal:
    internal: true

volumes:
  mongo:
  mongoc:

services:
  mongo:
    container_name: spotify_mongo
    image: mongo:4.2
    networks:
      - internal
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - mongo:/data/db
      - mongoc:/data/configdb
  node:
    container_name: spotify_app
    depends_on:
      - mongo
    environment:
      API_HOST: http://${SPOTIFY_URL:-localhost:8888}/callback
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      DATABASE_URL: mongodb://mongo/spotify
      LETSENCRYPT_HOST: ${SPOTIFY_URL}
      VIRTUAL_HOST: ${SPOTIFY_URL}
    image: luisenmarroquin/spotify-sync
    networks:
      - external
      - internal
    ports:
      - 8888
    restart: unless-stopped
  express:
    container_name: spotify_express
    depends_on:
      - node
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_SITE_COOKIESECRET: ${ME_COOKIE:-12345678}
      ME_CONFIG_SITE_SESSIONSECRET: ${ME_SESSION:-12345678}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME:-12345678}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD:-12345678}
      LETSENCRYPT_HOST: db.${SPOTIFY_URL}
      VIRTUAL_HOST: db.${SPOTIFY_URL}
    image: mongo-express:latest
    networks:
      - external
      - internal
    ports:
      - 8081
    restart: unless-stopped
