version: "3.7"

networks:
  external:
    name: nginx-proxy
  internal:
    internal: true

volumes:
  mongo:
  mongoc:

services:
  mongo:
    container_name: ${NAME_MONGO:-spotify_mongo}
    image: mongo:4.0
    networks:
      - internal
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - mongo:/data/db
      - mongoc:/data/configdb
  app:
    build: .
    container_name: ${NAME_APP:-spotify_app}
    depends_on:
      - mongo
    environment:
      API_HOST: http://${FULL_URL:-localhost:8888}/callback
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      DATABASE_URL: mongodb://mongo/spotify
      LETSENCRYPT_HOST: ${FULL_URL}
      VIRTUAL_HOST: ${FULL_URL}
    image: luisenmarroquin/spotify
    networks:
      - external
      - internal
    ports:
      - ${PORT_APP_CI:-8888:8888}
    restart: unless-stopped
  express:
    container_name: ${NAME_EXPRESS:-spotify_express}
    depends_on:
      - app
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${USERNAME:-12345678}
      ME_CONFIG_BASICAUTH_PASSWORD: ${PASSWORD:-12345678}
      ME_CONFIG_SITE_SESSIONSECRET: ${SESSIONSECRET:-12345678}
      ME_CONFIG_SITE_COOKIESECRET: ${COOKIESECRET:-12345678}
      LETSENCRYPT_HOST: db.${FULL_URL}
      VIRTUAL_HOST: db.${FULL_URL}
    image: mongo-express:latest
    networks:
      - external
      - internal
    ports:
      - ${PORT_EXP_CI:-8690:8081}
    restart: unless-stopped
