version: "3.5"

networks:
  external:
    name: nginx-proxy
  internal:
    internal: true

volumes:
  mongo:
  modules:

services:
  site:
    build: .
    command: /bin/sh -c 'node app.js'
    depends_on:
      - mongo
    environment:
      - API_HOST=http://${FULL_URL:-localhost:8888}/callback
      - DATABASE_URL=mongodb://mongo/spotify
      # Nginx SSL Proxy
      - VIRTUAL_HOST=${FULL_URL}
      - LETSENCRYPT_HOST=${FULL_URL}
      - LETSENCRYPT_EMAIL=${USER_EMAIL}
    networks:
      - external
      - internal
    ports:
      - ${PORT:-8888:8888}
    restart: unless-stopped
    volumes:
      - modules:/opt/app/node_modules
  mongo:
    image: mongo:latest
    networks:
      - internal
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - mongo:/data/db
  mongoexpress:
    depends_on:
      - mongo
    environment: 
      # HTTP Basic Auth # MongoDB Connection Auth Config
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: wh34f34eed5ma9ia
      ME_CONFIG_BASICAUTH_PASSWORD: atebw9abaf34em82
      ME_CONFIG_SITE_COOKIESECRET: ad3s585f46radxfh23424w
      ME_CONFIG_SITE_SESSIONSECRET: qrd2diosl3adh2334xf7kl
      # Nginx SSL Proxy
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
      LETSENCRYPT_HOST: db.${FULL_URL}
      VIRTUAL_HOST: db.${FULL_URL}
    image: mongo-express:latest
    networks:
      - external
      - internal
    ports:
      - 8081:8081
    restart: unless-stopped


