name: Deploy App

on:
  push:
    branches:
    - main

jobs:
  # github:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build files for GitHub Pages
  #     run: |
  #       npm ci --no-optional
  #       npm run browser
  #       cp CNAME public/CNAME
  #   - uses: LuisEnMarroquin/gh-pages-publish@v2.4.4
  #     with:
  #       FOLDER: public
  #       SSHKEY: ${{ secrets.SSH_GITHUB }}
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push image to Docker Hub
      run: |
        docker login -u luisenmarroquin -p ${{ secrets.DOCKER_PASSWORD }}
        docker build --tag luisenmarroquin/spotify-sync:latest .
        docker push luisenmarroquin/spotify-sync:latest
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        ORIGIN: spotify.marroquin.dev
        SSHKEY: ${{ secrets.SSH_SERVER }}
        NAME: production
        PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.SSH_USER }}
    - name: Set workplace in remote server
      run: |
        ssh production 'rm -rf /opt/.github/spotify && mkdir -p /opt/.github/spotify'
        sh dotenv.sh ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.ME_USERNAME }} ${{ secrets.ME_PASSWORD }} ${{ secrets.ME_SESSION }} ${{ secrets.ME_COOKIE }}
        scp .env compose.yml production:/opt/.github/spotify
    - name: Deploy project in remote server
      run: |
        ssh production 'cd /opt/.github/spotify && docker-compose -f compose.yml pull'
        ssh production 'cd /opt/.github/spotify && docker-compose -f compose.yml -p spotify up -d --remove-orphans'
        ssh production 'rm -rf /opt/.github/spotify'
