name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: npm ci
    - name: Compile and minify TypeScript
      run: npm run compile

    - name: Moving public/jquery
      run: mkdir public/jquery && cp -R node_modules/jquery/dist/* public/jquery/

    - name: Moving public/bootstrap
      run: mkdir public/bootstrap && cp -R node_modules/bootstrap/dist/* public/bootstrap/

    - name: Moving public/popper
      run: mkdir public/popper && cp -R node_modules/popper.js/dist/umd/* public/popper/

    - name: Copy CNAME to set custom URL
      run: cp CNAME public/CNAME
    - uses: LuisEnMarroquin/gh-pages-publish@v2.4.4
      with:
        FOLDER: public
        SSHKEY: ${{ secrets.SSH_GITHUB }}
