name: Self Hosted

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login -u luisenmarroquin -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build --tag luisenmarroquin/spotify-sync:latest .
    - run: docker push luisenmarroquin/spotify-sync:latest
    - uses: LuisEnMarroquin/setup-ssh-action@v1.8
      with:
        ORIGIN: spotify.marroquin.dev
        SSHKEY: ${{ secrets.SSH_SERVER }}
        NAME: production
        PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.SSH_USER }}
    - run: ssh production hostname
    - run: ssh production 'rm -rf /opt/.github/spotify && mkdir -p /opt/.github/spotify'
    - run: sh dotenv.sh ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.ME_USERNAME }} ${{ secrets.ME_PASSWORD }} ${{ secrets.ME_SESSION }} ${{ secrets.ME_COOKIE }}
    - run: scp .env compose.yml production:/opt/.github/spotify
    - run: ssh production docker-compose -v
    - run: ssh production 'cd /opt/.github/spotify && docker-compose -f compose.yml pull'
    - run: ssh production 'cd /opt/.github/spotify && docker-compose -f compose.yml --project-name spotify up -d --remove-orphans'
    - run: ssh production rm -rf /opt/.github/spotify
    - run: echo 'Exit code 0 is success and 1 is failure' && echo $?
