name: Nginx Proxy

on:
  push:
    branches:
    - proxy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        ORIGIN: whoami.marroquin.dev
        SSHKEY: ${{ secrets.SSH_SERVER }}
        NAME: production
        PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.SSH_USER }}
    - name: Set workplace in remote server
      run: |
        ssh production 'rm -rf /opt/.github/proxy && mkdir -p /opt/.github/proxy'
        scp compose-nginx.yml production:/opt/.github/proxy
    - name: Deploy project in remote server
      run: |
        ssh production 'cd /opt/.github/proxy && docker-compose -f compose-nginx.yml pull'
        ssh production 'cd /opt/.github/proxy && docker-compose -f compose-nginx.yml -p proxy up -d --remove-orphans'
        ssh production 'rm -rf /opt/.github/proxy'
